### PR TITLE
Create palette

### PR DESCRIPTION
**Pull request by kevnk**
This is a branch of the [Luminance/Lightness Toggle Pull Request](https://github.com/SimeonGriggs/tailwind-css-palette-generator/pull/3);

It essentially allows you to store multiple colors created in the app (and toggle pack to them to update them some more).

All explained here: https://www.loom.com/share/2590c074f58b42de82f55b42ac67523b

### CODE REVIEW

**Comment by kevnk** [comment]
I realized this doesn't preserve ALL of the tweaks... namely hue and saturation.  I'll reopen when I've got that working.

**Comment by kevnk** [comment]
Ok, this is fixed and ready to go

**Comment by SimeonGriggs** [comment]
This is very cool too, something I wanted to do and never got around to.

I haven't touched this project in awhile, think I'm keen to jump back in. 

Cheers!

**Comment by kevnk** [comment]
Haha awesome!

**Pull request merged**
