### PR TITLE
Luminance/Lightness Toggle

### PR DESCRIPTION
**Pull request by kevnk**
Hey Simeon,

I was wanting to make a tailwind color generator but with luminance instead of lightness. Your site/project was nearly exactly what I had envisioned (if not better!).

Here are some notes on what all is included in this pull request: https://www.loom.com/share/6b2c44a0f6394a2697108567316b32e4

All the best!

### CODE REVIEW

**Comment by SimeonGriggs** [comment]
Wow. Let me give this a look over!!

**Comment by kevnk** [comment]
For the record... I added a link to the footer... but that's not a big deal to me if it's a big deal to you... ;)

**Comment by SimeonGriggs** [comment]
I love it. Awesome work!

**Comment by kevnk** [comment]
Thanks so much!!

**Pull request merged**
